### ISSUE TITLE
Undefined offset: 0 in ... PickLastMinorVersionFromCollection

### ISSUE THREAD

**Issue by schmunk42** [Roave/BackwardCompatibilityCheck#114]
I add the the BCchecker locally to our project at https://github.com/dmstr/yii2-adminlte-asset

When I run the check in the container I get:

```
root@f5eb6f0ecb4d:/repo# vendor/bin/roave-backward-compatibility-check 
PHP Notice:  Undefined offset: 0 in /repo/vendor/roave/backward-compatibility-check/src/Git/PickLastMinorVersionFromCollection.php on line 48

Notice: Undefined offset: 0 in /repo/vendor/roave/backward-compatibility-check/src/Git/PickLastMinorVersionFromCollection.php on line 48
PHP Fatal error:  Uncaught TypeError: Return value of Roave\BackwardCompatibility\Git\PickLastMinorVersionFromCollection::forVersions() must be an instance of Version\Version, null returned in /repo/vendor/roave/backward-compatibility-check/src/Git/PickLastMinorVersionFromCollection.php:48
Stack trace:
#0 /repo/vendor/roave/backward-compatibility-check/src/Command/AssertBackwardsCompatible.php(226): Roave\BackwardCompatibility\Git\PickLastMinorVersionFromCollection->forVersions(Object(Version\VersionsCollection))
#1 /repo/vendor/roave/backward-compatibility-check/src/Command/AssertBackwardsCompatible.php(150): Roave\BackwardCompatibility\Command\AssertBackwardsCompatible->determineFromRevisionFromRepository(Object(Roave\BackwardCompatibility\Git\CheckedOutRepository), Object(Symfony\Component\Console\Output\StreamOutput))
#2 /repo/vendor/symfony/console/Command/Command.php(255): Roave\BackwardCompatibility\Command\AssertBackwardsCompatible->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Con in /repo/vendor/roave/backward-compatibility-check/src/Git/PickLastMinorVersionFromCollection.php on line 48

Fatal error: Uncaught TypeError: Return value of Roave\BackwardCompatibility\Git\PickLastMinorVersionFromCollection::forVersions() must be an instance of Version\Version, null returned in /repo/vendor/roave/backward-compatibility-check/src/Git/PickLastMinorVersionFromCollection.php:48
Stack trace:
#0 /repo/vendor/roave/backward-compatibility-check/src/Command/AssertBackwardsCompatible.php(226): Roave\BackwardCompatibility\Git\PickLastMinorVersionFromCollection->forVersions(Object(Version\VersionsCollection))
#1 /repo/vendor/roave/backward-compatibility-check/src/Command/AssertBackwardsCompatible.php(150): Roave\BackwardCompatibility\Command\AssertBackwardsCompatible->determineFromRevisionFromRepository(Object(Roave\BackwardCompatibility\Git\CheckedOutRepository), Object(Symfony\Component\Console\Output\StreamOutput))
#2 /repo/vendor/symfony/console/Command/Command.php(255): Roave\BackwardCompatibility\Command\AssertBackwardsCompatible->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Con in /repo/vendor/roave/backward-compatibility-check/src/Git/PickLastMinorVersionFromCollection.php on line 48
```

But we should have "enough" stable tags to compare...

```
root@f5eb6f0ecb4d:/repo# git tag
0.1.0
0.2.0
1.0.0
1.1.0
1.1.1
2.0.0
2.0.0-alpha1
2.0.0-beta1
2.1.0
2.1.1
2.1.2
2.1.3
2.2.0
2.2.1
2.2.2
2.2.3
2.2.4
2.3.0
2.3.1
2.3.2
2.3.3
2.3.4
2.4.0
2.4.0-beta1
2.4.0-rc1
2.4.1
2.4.2
2.4.3
2.4.4
2.5.0
2.5.0-rc1
2.6.0
2.6.1
2.6.2
2.7.0-beta1
3.0.0-alpha1
```

**Comment by Ocramius** [comment]
Can you check what is being passed in here, please?

https://github.com/Roave/BackwardCompatibilityCheck/blob/459e15befca19a2100b5f8e9c72a01f52c9c634d/src/Git/PickLastMinorVersionFromCollection.php#L24

**Comment by schmunk42** [comment]
This is the output for `var_dump($versions)`: https://gist.github.com/schmunk42/3b5aeab436a78cdc0b37a767b482d651

`$lastVersion` is

```
object(Version\Version)#1476 (5) {
  ["major":protected]=>
  int(3)
  ["minor":protected]=>
  int(0)
  ["patch":protected]=>
  int(0)
  ["preRelease":protected]=>
  object(Version\Extension\PreRelease)#1474 (1) {
    ["identifiers":"Version\Extension\BaseExtension":private]=>
    array(1) {
      [0]=>
      string(6) "alpha1"
    }
  }
  ["build":protected]=>
  object(Version\Extension\NoBuild)#1475 (1) {
    ["identifiers":"Version\Extension\BaseExtension":private]=>
    array(0) {
    }
  }
}
```

**Comment by Ocramius** [comment]
@schmunk42 I'm more interested about the state of `VersionCollection` itself: this may be an upstream bug.

**Comment by schmunk42** [comment]
Sorry, what do you mean with **state of `VersionCollection`**? Should I dump it at a later point?

**Comment by Ocramius** [comment]
Ideally, I'd need a test for `PickLastMinorVersionFromCollection`:

https://github.com/Roave/BackwardCompatibilityCheck/blob/991bf552792f6abdddf1831bf1a505acd8ce1a97/src/Git/PickLastMinorVersionFromCollection.php#L24-L49

To be placed in `PickLastMinorVersionFromCollectionTest`:

https://github.com/Roave/BackwardCompatibilityCheck/blob/991bf552792f6abdddf1831bf1a505acd8ce1a97/test/unit/Git/PickLastMinorVersionFromCollectionTest.php#L17

Such test would trigger the same warning you have.

As you can see, the test uses a list of versions in a collection:

https://github.com/Roave/BackwardCompatibilityCheck/blob/991bf552792f6abdddf1831bf1a505acd8ce1a97/test/unit/Git/PickLastMinorVersionFromCollectionTest.php#L47

**Comment by schmunk42** [comment]
I added a test with a similar version setup as shown above, the test fails also with `Undefined offset: 0`.

**Comment by Ocramius** [comment]
Moved into #118
